DROP DATABASE IF EXISTS devshop;
CREATE DATABASE devshop;
USE devshop;

DROP TABLE IF EXISTS projectAssignment;
DROP TABLE IF EXISTS employee;
DROP TABLE IF EXISTS project;


CREATE TABLE project (
  projectId INT UNSIGNED AUTO_INCREMENT NOT NULL,
  title VARCHAR(64) NOT NULL,
  startDate DATE NOT NULL,
  endDate DATE NOT NULL,
  PRIMARY KEY (projectId)
);


CREATE TABLE employee (
EmployeeId INT UNSIGNED AUTO_INCREMENT NOT NULL,
FirstName CHAR(32) NOT NULL,
LastName CHAR(32) NOT NULL,
AccessLevelId VARCHAR(4) NOT NULL,
Address1 VARCHAR(64) NOT NULL,
Address2 VARCHAR(64) NOT NULL,
City VARCHAR(16) NOT NULL,
State CHAR(2) NOT NULL,
Zip VARCHAR(5) NOT NULL,
Phone VARCHAR(20) NOT NULL,
Status CHAR(16) NOT NULL,
Email VARCHAR(64) NOT NULL,
Salt CHAR(64) NOT NULL,
Hash CHAR(128) NOT NULL,
PRIMARY KEY (employeeId)
);

CREATE TABLE projectAssignment (
employAlot DECIMAL(6,2) NOT NULL,
projectId INT UNSIGNED NOT NULL,
employeeId INT UNSIGNED NOT NULL,
INDEX (projectId),
INDEX (employeeId),
FOREIGN KEY (projectId) REFERENCES project(projectId),
FOREIGN KEY (employeeId) REFERENCES employee(employeeId),
PRIMARY KEY (projectId, employeeId)
);